version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "monorepo-fem--scryscraper--dev"
resolve_s3 = true
s3_prefix = "monorepo-fem--scryscraper--dev"
region = "ap-southeast-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
