version = 0.1
[default.deploy.parameters]
stack_name = "ts-cloudwatch-publisher-dev"
resolve_s3 = true
s3_prefix = "ts-cloudwatch-publisher-dev"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" ScheduleRate=\"rate(1 minute)\" LogRetentionDays=\"7\""
image_repositories = []
